### ISSUE TITLE
Latest version is v1

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FantasticFiasco/action-update-license-year#122]
On the action page on marketplace (https://github.com/marketplace/actions/update-license-copyright-year-s), the latest version is indicated as **v1**.

![image](https://user-images.githubusercontent.com/19204050/104347892-086ec880-54f9-11eb-93a4-c2784b112ada.png)

I noticed this already when I first used the action, however, I also noticed that there are newer [GitHub releases](https://github.com/FantasticFiasco/action-update-license-year/releases). So why is that?

**Comment by FantasticFiasco** [comment]
Damn, you are correct. I'm in the process of releasing the feature you wanted, let me se if I can correct the marketplace at the same time. Thanks for the heads up!

**Comment by FantasticFiasco** [comment]
It seems that the license agreement for publishing a release to the marketplace had changed, and I hadn't accepted those changes.

Now I have, because of you, and it seems that the marketplace correctly has been updated to show my latest version.

![image](https://user-images.githubusercontent.com/8513095/104366801-344e7600-551a-11eb-9ef8-c98d39518280.png)

**Comment by creativecreatorormaybenot** [comment]
@FantasticFiasco That is super awesome 🚀
