### ISSUE TITLE
Description is unclear.

### ISSUE THREAD

**Issue by alex4200** [FantasticFiasco/action-update-license-year#158]
**Is your feature request related to a problem? Please describe.**

I have found a description on how to update the copyright in a LICENSE file [HERE(https://github.com/marketplace/actions/update-license-copyright-year-s). But the description is not clear to me. 

**Describe the solution you'd like**

A clear description of  what I really need to do. I mean, there is a file snippet in a section `Super simple to use`, and there is a file snippet in a different section  `Usage`. Now I need two files? Where to put them? Also, in the scenarios below there is a *third* file snippet. I am totally confused. I do not know at all what to do.

Also, does this only update the copyright in a LICENSE file?
How to make that script/github action also update the COPYRIGHT in a README file? 
Also, how can I use that action to update the copyright in EACH github repository beloning to an organization?

**Comment by FantasticFiasco** [comment]
Hi @alex4200 and thanks for the feedback!

I think many of the answers comes down to usage of GitHub Actions in general, but I can see where you're coming from. I'm guessing that this would be the first GitHub Action workflow you create? Is that a correct assumption? I ask because I'm afraid that the documentation is written for someone familial with GitHub Actions. I might have to add more documentation for developers unfamiliar with the topic to be really inclusive, and not scare away developers.

Regarding `Super simple to use`, these are the GitHub Actions steps you should add in your workflow to use this action. Would you benefit from having a complete minimal workflow specified instead of only the steps?

Regarding `Usage`, would renaming the chapter to `API` be better?

Regarding `Scenarios`, this chapter has a lot of examples for different situations, and my hope is that one of these examples fit your requirement, meaning that you can copy the configuration to your workflow.

**Comment by alex4200** [comment]
Hello, yes your assumption is correct, I have never worked with github actions before. 

After having looked into a tutorial it is more clear to me. But maybe you can add a short note under the section `Usage` that here now you describe the complete usage structure of what a user can do. Then it would be clear that the snippet under `Super simple to use` is just a minimalistic example of that. Yes, and maybe `API` would make that even clearer. 

However, do you know if it is possible to create an action to update the copyright in **every** repository for an organization? Or does this require a github action in every repository?

**Comment by FantasticFiasco** [comment]
GitHub Actions is scoped to the repository, i.e. you will have to add the same workflow to every repository in the organization.

**Comment by alex4200** [comment]
Thanks for the clarification
